- README.md
- src/components/Button.jsx
- src/components/Carousel.jsx
- src/components/Sidebar.jsx
- src/components/index.js
README file updated with notes as agreed upon by the FE team.
> updated README file

- src/App.js
- src/components/Carousel.jsx
- src/components/InputField.jsx
- src/components/Navbar.jsx
- src/index.css
- src/pages/CreateOrg.jsx
- src/pages/Home.jsx
- src/pages/index.js
- src/theme.js
Made the following changes:
- Added create organization page
- Added carousel component
- Fixed styling issues in input field and navbar components
> made changes

- src/components/Navbar.jsx
- src/components/Textbox.jsx
- src/index.css
- src/pages/Category.jsx
Made the following changes:
- Fixed styling issues for the logo in the navbar
- Added a grid display to the category page
> made changes to the category page

- src/components/LoadingSpinner.jsx
- src/components/index.js
- src/index.css
- src/pages/Home.jsx
- src/redux/features/api/apiSlice.js
- Added the fetch functionality in redux to fetch the API list, endpoint not provided yet
- added the loading spinner component
> added fetch funtionality for apis in redux; added loading spinner

- package-lock.json
- package.json
- src/App.js
- src/components/ApiDetails.jsx
- src/pages/CreateOrg.jsx
- src/pages/SingleApi.jsx
Created the organization page and made a little correction on the Singe Api Page.
> Created organization page and Single Api page

- package-lock.json
- src/App.js
- src/components/Navbar.jsx
- src/pages/SignupPage.jsx
- added SignupPage
- added username state for username input field
- created error state to show error when username and password field is empty
- added facebook icon to the signup page
- added code to show signup button on the navbar when user is  not logged in 
- comment out the search in the app.js (it was interfering with the code)
> added SignupPage

- package-lock.json
- package.json
- src/App.js
- src/components/Navbar.jsx
- src/components/NavbarAuth.jsx
- src/components/index.js
- src/pages/Home.jsx
- src/pages/LoginPage.jsx
- src/pages/Signup.jsx
- created a navbar for the authentication page (login & signup)
- added new section to the signup page
> created an authentication navbar and added some code to the signup page

- src/components/Navbar.jsx
- src/components/Sidebar.jsx
- src/components/Textbox.jsx
- src/index.css
- src/pages/Category.jsx
- src/pages/Home.jsx
Some components were not responsive so I made style changes.
> made style changes for responsiveness

- src/App.js
- src/components/UserHeader.jsx
- src/pages/LoginPage.jsx
- src/pages/UserProfile.jsx
- src/services/loginService.js
- The login feature working fine
- The user's data can be saved to the local storage by checking the checkbox on the login page
- Added a function to check the local storage for user data and log a user in automatically.
> done with the login feature

- package-lock.json
- package.json
- src/pages/Signup.jsx
- src/redux/features/user/userSlice.js
- src/services/signupService.js
Please check the code for review
> check for review

- src/components/Navbar.jsx
- src/pages/CreateOrg.jsx
- src/services/organizationService.js
I worked on CreateOrg.jsx, I created a file organizationService in the service folder and I rendered the CreateOrg.jsx on the NavBar
@PhilemonBrain @pablo-clueless
> Organization Page

- src/pages/CreateOrg.jsx
- src/services/organizationService.js
Create organization is now functional. 
@PhilemonBrain @taiwoAkindele
> Create Organization is working

- src/components/UserMenu.jsx
- src/pages/LoginPage.jsx
the userSlice in the redux was not receiving the data from the login dispatch so I updated the code
> profile page is now working fine

- src/App.js
- src/components/ApiPageSidebar.jsx
- src/components/MyApis.jsx
- src/components/UserMenu.jsx
- src/pages/ApiEndpoint.jsx
- src/pages/MyApiPage.jsx
- src/services/endpointService.js
endpoint page is working fine
still need to work on some styling
> Endpoint page

- src/App.js
- src/pages/LoginPage.jsx
- src/pages/MyApiPage.jsx
- src/pages/OrgList.jsx
- src/services/apiService.js
> orgs-list page created

- src/App.js
- src/components/ApiPageSidebar.jsx
- src/components/OrganizationList.jsx
- src/components/PricingTable.jsx
- src/pages/Endpoint.jsx
- src/pages/OrgList.jsx
updated orglist to show only those a user is subscribed to
> added authentication guard & updated orgList

- src/hooks/fetch-hook.js
- src/pages/LoginPage.jsx
- src/redux/features/api/apiSlice.js
- src/redux/features/singleApi/singleApiSlice.js
> added utility fetch hook

- src/components/AddNewMenu.jsx
- src/components/Textbox.jsx
- src/pages/Category.jsx
apis are now present in the categories
> Post method

- src/components/PopUp.jsx
- src/components/Pricing.jsx
- src/components/PricingTable.jsx
- src/components/index.js
- src/pages/Home.jsx
- src/pages/SingleApi.jsx
- src/redux/features/subscription/subscriptionSlice.js
- src/redux/store.js
- src/services/subscriptionService.js
- src/services/unsubscribeService.js
Added popup component whenever user subscribes or unsubscribes
PS: There is a bug - if I reload, the subscription info goes and the button becomes subscribe again. There should be a way for the subscription data to be fetched and effect in the buttons.
> added subscription popup

- src/App.js
- src/components/OrgTeammates.jsx
- src/components/OrganizationInvite.jsx
- src/components/OrganizationList.jsx
- src/pages/CreateOrg.jsx
- src/pages/OrganizationPage.jsx
- src/services/addUserOrgService.js
User can now be added to an organization from the page navigated to after creating an organization and from my api page.
display a better information about the user added like name or email. Right now it shows only role.
> User can be added to an organization

- src/App.js
- src/components/Navbar.jsx
- src/pages/LoginPage.jsx
Cookies are being set on login and removed on logout to keep user information safe.
> added cookies for login

- src/components/Endpoints.jsx
- src/pages/SingleApi.jsx
> Pricing page data match and SingleAPI page endpoints updated

- src/pages/ApiEndpoint.jsx
User can add both single endpoint and multiple all at once when using  the POST method
> User can add both single endpoint and multiple all at once

- package-lock.json
- package.json
- src/App.js
- src/index.css
- src/pages/EmailVerify.jsx
- src/pages/ForgotPassword.jsx
- src/pages/PasswordReset.jsx
I created pages for password reset and email verify
> created pages for password reset and email verify

- src/App.js
- src/pages/ChangePassword.jsx
- src/pages/PasswordReset.jsx
- Edited Routing Page
- Finished Password Reset Page
- Finished Change Password Page
> Forgot Password Flow Cleared

- src/App.js
- src/components/OrgTeammates.jsx
- src/components/OrganizationInvite.jsx
- src/components/OrganizationList.jsx
> Organization bugs Fixed

- src/components/Pricing.jsx
- src/components/PricingTable.jsx
- src/components/SubscribedApiProfile.jsx
- src/pages/SingleApi.jsx
> Cleared all console errors in Pricing and SingleApi section, With stretch and overflow fix

- src/pages/ChangePassword.jsx
- src/pages/PasswordReset.jsx
- Made fixes to change password and reset password as corrected by tijani
> change password and reset password fixes
